### PR TITLE
Mobile version of site

### LINKED ISSUE #14: Mobile version?
So, mostly our visitors would likely be using phones (including me), so should there be a mobile CSS?

### PR DESCRIPTION
**Pull request by Mrcomputer1**
I have made a mobile version of the site!
I could not test it on a mobile device because my iPod would not connect to my test server on my laptop and it ran out of battery :angry:

To test
1. Install a web server on your computer
2. In the root run git clone https://github.com/iliketocode/bored.git
3. In the new folder "bored" run git checkout Mrcomputer1-mobile
NOTE: You must have it installed in a folder called "bored" in the root of the web server so the address is yourwebserveraddress/bored/ (Examples: www*.*webserver.com/bored/, localhost/bored/, 000.000.0.000/bored/)

This pull request closes #14 

To merge both @DrKat123 and @iliketocode  must like

### CODE REVIEW

**Comment by DrKat123** [comment]
Testing this using Apache and Micro$wag WebMatrix 3

**Comment by Mrcomputer1** [comment]
@DrKat123 I made some changes. Can you check them?

**Comment by DrKat123** [comment]
1. It seems ok
2. Ok
2. Where's the footer file?
4. ok

**Comment by Mrcomputer1** [comment]
The footer file should be _footer.html

**Comment by iliketocode** [comment]
Want me to merge the pull request then?

**Comment by Mrcomputer1** [comment]
@iliketocode / @funsites yes

**Comment by DrKat123** [comment]
I'll merge it

**Pull request merged**
