### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### iliketocode/bored now has a Chat Room on Gitter

@DrKat123 has just created a chat room. You can visit it here: [https://gitter.im/iliketocode/bored](https://gitter.im/iliketocode/bored?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/iliketocode/bored?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by DrKat123** [comment]
The official chat room for this repo
We don't need to discuss in the issues

**Comment by Mrcomputer1** [comment]
Cool!

**Comment by DrKat123** [comment]
So i'll wait until @iliketocode likes this :stuck_out_tongue_closed_eyes:

**Comment by iliketocode** [comment]
Lol sorry! Been busy on my other account @funsites which is now an admin!

**Pull request merged**
