### PR TITLE
Created a .htaccess file for custom error pages

### PR DESCRIPTION
**Pull request by DrKat123**
I'll make the 404.html later

### CODE REVIEW

**Comment by Mrcomputer1** [comment]
I don't think .htaccess works on Github. You just need to have a 404.html. Also 404.html only works at *.github.io not *.github.io/*

**Comment by DrKat123** [comment]
Hmm, yes.
I might make a copy on Gwiddle

**Comment by Mrcomputer1** [comment]
Maybe @iliketocode could put the 404.html in a iliketocode.github.io repo?

**Comment by iliketocode** [comment]
@Mrcomputer1 Sure!

**Pull request merged**
