### PR TITLE
Fonts

### PR DESCRIPTION
**Pull request by DrKat123**
Replaced fonts

### CODE REVIEW

**Comment by DrKat123** [comment]
Hello?

**Comment by Mrcomputer1** [comment]
I think the change is good.

Pics of change: [Current Site Font](http://u.cubeupload.com/Mrcomputer1/Screenshot980.png) || [Site with new font](http://u.cubeupload.com/Mrcomputer1/Screenshot981.png)

**Comment by DrKat123** [comment]
@Mrcomputer1 so i'll merge this then. Btw i can also help with the css

**Comment by Mrcomputer1** [comment]
You didn't give @iliketocode a chance to look at it :P

**Comment by DrKat123** [comment]
O yeah i forgot. Should this be undoed?

**Comment by Mrcomputer1** [comment]
@DrKat123 No. If @iliketocode does not like it they can undo the change if they want.

**Comment by iliketocode** [comment]
Looking great!

**Comment by DrKat123** [comment]
Thanks!

**Pull request merged**
